### PR TITLE
v3.0 release

### PR DESCRIPTION
**Pull request by radek-k**
### Common/Graphics:
- [x] Redesign FFmpeg loader and improve exception messages.
- [x] Create a new class for multimedia metadata.
- [x] Add `UYVY422` format support (#26)
- [x] Merge `VideoPixelFormat` and `ImagePixelFormat` format 

### Decoding:
- [x] Delete the current unused packet queue implementation.
- [x] Improve frame decoding performance.
- [x] Use average frame rate for FrameCount calculation.
- [x] Fix the AccessViolationException in ImageConverter.AVFrameToBitmap method.

### Encoding:
- [x] Fix a crash when disposing `MediaOutput`.
- [x] Fix the invalid DTS error when disposing H.264/H.265 encoder.
- [x] Add option to set PTS for a new frame. (#23)
- [x] Add an option to apply custom flags when creating a container.
- [x] Add an option to set metadata in container.
- [x] Create a new video codec enum with only supported codecs (instead of `FFmpeg.AutoGen.AVCodecID`)
- [x] Throw an exception when attempt to use the `x264` encoder with LGPL FFmpeg binaries.
- [x] Add an option to specify a container format independently from target file name.
- [x] Support CRF and preset settings (H.264/H.265 codec)

### CODE REVIEW

**Comment by dev-masih** [comment]
can you please release the v3 sooner the crashes are killing me

**Comment by dev-masih** [comment]
using `develop` branch I see that when creating a `MediaBuilder` it creates an `OutputContainer` with `ContainerOptions` equals to `null`. so when after that using this media builder to create a video it crashes.

```
MediaBuilder mediaBuilder = MediaBuilder.CreateContainer("output.mp4", ContainerFormat.MP4);
MediaOutput outputFile = mediaBuilder.WithVideo(outputSettings).Create();
```

**Comment by radek-k** [comment]
@dev-masih Are you getting the AccessViolationException when reading video frames using the `develop` branch after recent commits?

**Comment by dev-masih** [comment]
OK i tested the develop branch and it seems that access violation error is now fixed, I tried several scenarios that caused access violation in the past but all of them seem ok to me.
one thing though, frame count is still not actually 100% correct. in my example, I tried to read the frame 897 and it hit with EndOfStreamException but Video.Info.FrameCount returned 901. but i don't know there is a way to fix this other than reading frames in a try block and catching the EndOfStreamException exception.
good job on the project btw.

**Comment by dev-masih** [comment]
and one more thing before the merge is to fix the documentation in README about `MediaBuilder` as it changed slightly who it creates the media

**Comment by dev-masih** [comment]
ping

**Comment by TechnikEmpire** [comment]
> ping

Generally, people contribute to open source projects by submitting pull requests. Are you paying the dev cause you're pinging him and making requests like you're playing an order, and everyone else watching the repo is getting spammed with it.

**Pull request merged**
